
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
  instance:
    instance:
      instanceid:
 ${eurl}:${spring.application.name}:${spring.application.instance_id:${server.port}}}
